info:
  id: ${spring.application.name}
logging:
  config: classpath:logback-spring-dev.xml
  level:
    org:
      springframework:
        security: ERROR
    com:
      netflix:
        eureka: ERROR
        discovery: ERROR
spring:
  security:
    user:
      name: admin
      password: admin123
eureka:
  server:
    evictionIntervalTimerInMs: 5000
  instance:
    preferIpAddress: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
  client:
    register-with-eureka: false
    fetch-registry: true
    registry-fetch-interval-seconds: 10
    eureka-service-url-poll-interval-seconds: 10
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8700/eureka/
      #,http://${spring.security.user.name}:${spring.security.user.password}@localhost:8801/eureka/